version: "3.6"
services:
  postgres:
    container_name: trainmedb
    image: postgis/postgis
    platform: linux/amd64  # Emulate amd64
    ports:
      - "7452:5432"
    volumes:
      - trainme-data:/var/lib/postgresql/data
      - /tmp:/tmp
    env_file:
      - .env.local
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
volumes:
  trainme-data:
    external: true
    name: trainme-data

