version: "3.6"
services:
  postgres:
    container_name: trainmedb
    image: postgis/postgis:16-3.4
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64  
    ports:
      - "7452:5432"
    volumes:
      - trainme-data:/var/lib/postgresql/data
      - /tmp:/tmp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=trainme
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
volumes:
  trainme-data:
    external: true
    name: trainme-data

