name: DB Migration

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.4.0 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Debug database connection
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: |
          echo "DATABASE_URL is set to: ${DATABASE_URL}"
          psql $DATABASE_URL --command="SELECT NOW();"

      - name: DB Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: |
          echo "convert migrations ${DATABASE_URL}"
          pnpm -w run convert-migrations
          echo "deploy migrations ${DATABASE_URL}"
          pnpm dlx prisma migrate deploy
        timeout-minutes: 5

      - name: Seed database
        run: pnpm --filter @trainme/db run seed
