# This workflow do the prisma migration deploy to supabase, for preview.

name: Production DB Migration

on:
  push:
    branches:
      - 'main'
    paths:
      - 'db/prisma/**'

defaults:
  run:
    working-directory: ./db

jobs:
  db-migration:
    uses: ./.github/workflows/job-db-migration.yml
    with:
      environment: production
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
      DIRECT_URL: ${{ secrets.DIRECT_URL_PRODUCTION }}