# This workflow do the prisma migration deploy to supabase, for preview.

name: Preview DB Migration

on:
  push:
    tags:
      - 'db-*'

  pull_request:
    branches:
      - '**'
      - '!main'

defaults:
  run:
    working-directory: ./db

jobs:
  db-migration:
    uses: ./.github/workflows/job-db-migration.yml
    with:
      environment: preview
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL_PREVIEW }}
      DIRECT_URL: ${{ secrets.DIRECT_URL_PREVIEW }}