name: Deploy to Vercel Preview

on:
  push:
    tags:
      - 'preview-*'
  pull_request:
    branches:
      - '**'
      - '!main'

defaults:
  run:
    working-directory: ./webapp

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  build:
    uses: ./.github/workflows/job-vercel-build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --token ${{ env.VERCEL_TOKEN }}
