name: Development Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: pnpm install

      # Run linting
      - name: Run Lint
        run: pnpm lint

      # Run tests
      # - name: Run Tests
        # run: pnpm test 

      # Build the application 
      - name: Build Application
        run: pnpm build 


