name: Vercel Deploy

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.4.0 --activate

      - name: Install dependencies
        run: pnpm install --filter @trainme/webapp

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: webapp/.next
          key: ${{ runner.os }}-build-${{ hashFiles('webapp/.next/**/*') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm test --filter @trainme/webapp
