name: Development Workflow

on:
  push:
    branches:
      - 'develop'

defaults:
  run:
    working-directory: ./db

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]


    environment: Preview

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install --filter=@brikmate/db

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: pnpm run convert-migrations && npx prisma migrate deploy --env-file .env.local