# This workflow do the prisma migration deploy to supabase, for preview.

name: Preview

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

defaults:
  run:
    working-directory: ./db

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: preview

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Debug database connection
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          psql ${{ secrets.DATABASE_URL }} --command="SELECT NOW();"

      - name: DB Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DATABASE_URL }}
        run: |
          pnpm -w run convert-migrations
          pnpm dlx prisma migrate deploy --preview-feature
        timeout-minutes: 1

      - name: Seed database
        run: pnpm -w run seed        
