# This workflow do the prisma migration deploy to supabase, for preview.

name: Development Workflow

on:
  push:
    tags:
      - 'dev-*'

defaults:
  run:
    working-directory: ./db

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]


    environment: Preview

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install --filter=@trainme/db

      - name: Check Database Connection
        run: |
          echo "Attempting to connect to the database..."
          # Replace `psql` command below with whatever database operation you are performing
          psql ${{ secrets.DATABASE_URL }} -c "SELECT 1;" || exit 1
          echo "Database connection successful."


      - name: DB Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: pnpm -w run convert-migrations && npx prisma migrate deploy
        