# This workflow do the prisma migration deploy to supabase, for preview.

name: Preview

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'

defaults:
  run:
    working-directory: ./db

env:
  NODE_ENV: production
  DATABASE_URL: ${{ secrets.DATABASE_URL_PREVIEW }}
  DIRECT_URL: ${{ secrets.DIRECT_URL_PREVIEW }}

jobs:
  use-shared-steps:
    uses: ./.github/workflows/db-migration.yml
    with:
      working-directory: ./db
