# This workflow do the prisma migration deploy to supabase, for preview.

name: Preview

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'

defaults:
  run:
    working-directory: ./db

jobs:
  call-shared-jobs:
    uses: ./.github/workflows/db-migration.yml
    with:
      environment: PREVIEW
