# This workflow do the prisma migration deploy to supabase, for preview.

name: Preview

on:
  push:
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> fa3cc6b (different CI/CD trigger)
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'
<<<<<<< HEAD
=======
    tags:
      - 'db-*'
>>>>>>> 48309cc (fixing build)
=======
>>>>>>> fa3cc6b (different CI/CD trigger)

defaults:
  run:
    working-directory: ./db

jobs:
<<<<<<< HEAD
  call-shared-jobs:
    uses: ./.github/workflows/jobs/db-migration.yml
    with:
      environment: preview
=======
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: preview

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.1 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Debug database connection
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          psql ${{ secrets.DATABASE_URL }} --command="SELECT NOW();"

      - name: DB Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DATABASE_URL }}
        run: |
          pnpm -w run convert-migrations
          pnpm dlx prisma migrate deploy --preview-feature
        timeout-minutes: 1

      - name: Seed database
        run: pnpm -w run seed        
>>>>>>> 48309cc (fixing build)
