# This workflow do the prisma migration deploy to supabase, for preview.

name: Production

on:
  push:
    branches:
      - 'main'
    paths:
      - 'db/prisma/**'

defaults:
  run:
    working-directory: ./db

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
      DIRECT_URL: ${{ secrets.DIRECT_URL_PRODUCTION }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.4.0 --activate

      - name: Install dependencies
        run: pnpm install --filter @trainme/db

      - name: DB Migrations
        run: |
          pnpm -w run convert-migrations
          pnpm dlx prisma migrate deploy
        timeout-minutes: 5

      - name: Seed database
        run: |
          node dist/seed.js