# This workflow do the prisma migration deploy to supabase, for preview.

name: Production

on:
  push:
    branches:
      - 'main'
    paths:
      - 'db/prisma/**'

defaults:
  run:
    working-directory: ./db

jobs:
  call-shared-jobs:
    uses: ./.github/workflows/db-migration.yml
    with:
      environment: PRODUCTION
